#!/usr/bin/env bash
set -eEuo pipefail

debug(){
	if ((DEBUG));then
		1>&2 printf 'DEBUG: %s\n' "$@"
	fi
}

set_git_infos() {
	# Git commits
	local line
	while IFS='' read -r line; do GIT_ACTUAL_TAGS+=("$line"); done < <(git tag --points-at 2> /dev/null || true)
	debug "Actuals tags :" "${GIT_ACTUAL_TAGS[@]:-}"
	GIT_ACTUAL_TAG="${CHANGELOG_TAG:-${GIT_ACTUAL_TAGS[0]:-}}"
	debug "Actual tag :" "${GIT_ACTUAL_TAG:-}"
	while IFS='' read -r line; do GIT_PREVIOUS_TAGS+=("$line"); done < <(git for-each-ref --no-contains=HEAD --sort=-creatordate --format '%(refname)' refs/tags 2> /dev/null | sed 's/refs\/tags\///')
	debug "Previous tags:" "${GIT_PREVIOUS_TAGS[@]}"
	GIT_PREVIOUS_TAG="${GIT_PREVIOUS_TAGS[0]:-}"
	debug "Previous tag:" "${GIT_PREVIOUS_TAG}"
}

set_user_config() {
	local user_conf
	if [ -f "${CONFIG_DIR}/config" ];then
		debug "User config found in ${CONFIG_DIR}, loading it..."
		user_conf=$(<"${CONFIG_DIR}/config")
	fi
	local repo_conf
	if [ -f "${GIT_TOP_LEVEL}/.git-changelog" ];then
		debug "Repo config found in ${GIT_TOP_LEVEL}, loading it..."
		repo_conf=$(<"${GIT_TOP_LEVEL}/.git-changelog")
	fi
	source /dev/stdin <<-EOF
		set_tpl_vars() {
			: \${hash:=}
			: \${tag:=}
			: \${title:=}
			: \${type:=}
			: \${scope:=}
			show_scope=
			header_tpl=('%s\n\n' 'CHANGELOG')
			release_tpl=('%s\n\n' "\${tag}")
			unreleased_tpl=('%s\n\n' 'Unreleased')
			type_tpl=('%s\n\n' "\${type}")
			scope_tpl=('%s\n\n' "\${scope}")
			commit_tpl=('- %s (%.7s)\n' "\${title}" "\${hash}")
			${user_conf:-}
			${repo_conf:-}
		}
	EOF
}


set_commit_infos() {
	debug "Loop over commits..."
	local commit_infos
	local commit_hash
	local commit_subject
	local commit_body
	local commit_type
	local commit_breaking
	local commit_scope
	local commit_title
	local i=0
	while IFS= read -r -d $'\0' commit_infos; do
		eval "$commit_infos"
		if [[ "${commit_subject}" =~ $CONVENTIONAL_COMMIT_REGEX ]];then
			debug "OK : conventional commit found in subject : '${commit_subject}' (${commit_hash::7})"
			commit_type="${BASH_REMATCH[1]}"
			commit_breaking="${BASH_REMATCH[4]}"
			commit_scope="${BASH_REMATCH[3]}"
			commit_title="${BASH_REMATCH[5]}"
			if [[ -n "${commit_breaking}" ]];then
				debug "OK : BREAKING CHANGE found in title : '${commit_subject}' (${commit_hash::7})"
				commit_type="BREAKING_CHANGES"
			else
				local line
				while IFS='' read -r line; do
					local regex="^BREAKING[ -]CHANGE:"
					if [[ "$line" =~ $regex ]];then
						debug "OK : BREAKING CHANGE found in body : '${commit_body}' (${commit_hash::7})"
						commit_type="BREAKING_CHANGES"
					fi
				done <<<"${commit_body}"
			fi
			# shellcheck disable=SC2076
			if [[ " ${CONVENTIONAL_COMMIT_TO_SHOW[*]} " == *" ${commit_type} "* ]]; then
				debug "OK : Commit type '$commit_type' is in \$CONVENTIONAL_COMMIT_TO_SHOW"
				COMMIT_HASH[$i]="$commit_hash"
				COMMIT_TITLE[$i]="$commit_title"
				COMMIT_BODY[$i]="$commit_body"
				COMMIT_SCOPE[$i]="${commit_scope:=no scope}"
				COMMIT_TYPE_LIST["$commit_type"]="${COMMIT_TYPE_LIST[$commit_type]:-} $i"
				COMMIT_SCOPE_LIST["$commit_scope"]="${COMMIT_SCOPE_LIST[${commit_scope}]:-} $i"
				((i=i+1))
			else
				debug "WARNING : Commit type '${commit_type}' not in \$CONVENTIONAL_COMMIT_TO_SHOW"
			fi
		else
			debug "WARNING : not a conventional commit with subject	'${commit_subject}' (${commit_hash::7})"
		fi
	done < <(git log -z	--pretty="IFS='' read -d '' -r commit_hash <<EOF ||	true%n%H%nEOF%nIFS='' read -d '' -r commit_subject <<EOF ||	true%n%s%nEOF%nIFS='' read -d	'' -r commit_body <<EOF || true%n%bEOF"	${GIT_PREVIOUS_TAG:+${GIT_PREVIOUS_TAG}..HEAD} 2>/dev/null)
}

set_changelog_release() {
	debug "Writing changelog.."
	local tag="${GIT_ACTUAL_TAG}"
	local show_scope
	set_tpl_vars
	if [[ -n "${tag:-}" ]];then
		# shellcheck disable=SC2059,SC2154
		printf -v output -- "${output:-}## ${release_tpl[0]}" "${release_tpl[@]:1}"
	else
		# shellcheck disable=SC2059,SC2154
		printf -v output -- "${output:-}## ${unreleased_tpl[0]}" "${unreleased_tpl[@]:1}"
	fi

	local type
	for type in "${CONVENTIONAL_COMMIT_TO_SHOW[@]}";do
		debug "Processing commit type: $type"
		if [[ -n "${COMMIT_TYPE_LIST[$type]:-}" ]];then
			local commit_list
			IFS=" " read -r -a commit_list <<< "${COMMIT_TYPE_LIST[$type]}"
			debug "commits with type : $type" "${commit_list[@]}"
			set_tpl_vars
			# shellcheck disable=SC2059,SC2154
			printf -v output -- "${output}### ${type_tpl[0]}" "${type_tpl[@]:1}"
			if [ -n "${show_scope}" ];then
				while IFS= read -r scope;do
					set_tpl_vars
					local scope_commits=()
					for commit in "${commit_list[@]}";do
						if [[ " ${COMMIT_SCOPE_LIST["$scope"]} " == *" ${commit} "* ]];then
							scope_commits+=("$commit")
						fi
					done
					debug "commits with scope : $scope" "${scope_commits[@]}"
					if [ "${#scope_commits[@]}" -gt 0 ];then
						# shellcheck disable=SC2059,SC2154
						printf -v output -- "${output}#### ${scope_tpl[0]}" "${scope_tpl[@]:1}"
						set_changelog_release_commits "${scope_commits[@]}"
					fi
				done < <(printf '%s\n' "${!COMMIT_SCOPE_LIST[@]}" | LC_ALL=C sort)
			else
				set_changelog_release_commits "${commit_list[@]}"
			fi
		else
			debug "No commit found with type : ${type}"
		fi
	done
}

set_changelog_release_commits() {
	commits=("$@")
	local i
	for i in "${commits[@]}";do
		local hash="${COMMIT_HASH[$i]}"
		debug "commit : ${hash}"
		local title="${COMMIT_TITLE[$i]}"
		debug "commit message : ${title}"
		set_tpl_vars
		# shellcheck disable=SC2059,SC2154
		printf -v output -- "${output}${commit_tpl[0]}" "${commit_tpl[@]:1}"
	done
	# shellcheck disable=SC2059
	printf -v output -- "${output}\n"
}

update_changelog() {
	# Used with sed to delete old section in CHANGELOG
	local escaped_header
	local escaped_release
	local escaped_unreleased
	local changelog_cleaned
	local line
	# shellcheck disable=SC2059
	escaped_header=$(printf -- "${header_tpl[0]:-}" "${header_tpl[@]:1}" | sed	's/[.[\/\*^$]/\\&/g')
	# shellcheck disable=SC2059
	escaped_release=$(printf -- "${release_tpl[0]:-}" "${release_tpl[@]:1}" | sed	's/[.[\/\*^$]/\\&/g')
	# shellcheck disable=SC2059
	escaped_unreleased=$(printf -- "${unreleased_tpl[0]:-}" "${unreleased_tpl[@]:1}" |	sed	's/[.[\/\*^$]/\\&/g')

	touch "${CHANGELOG_PATH}"

	# header
	while IFS= read -r line;do
		changelog_cleaned+=( "$line" )
	done < <(
		# shellcheck disable=SC2059
		printf -- "# ${header_tpl[0]}" "${header_tpl[@]:1}" \
		&& printf '\0'
	)

	# new
	while IFS= read -r line;do
		changelog_cleaned+=( "$line" )
	done < <(
		printf '%s' "$output" \
		&& printf '\0'
	)

	# old
	while IFS= read -r line;do
		changelog_cleaned+=( "$line" )
	done < <(
		sed \
			-e '$a## ' "${CHANGELOG_PATH}" | \
		sed \
			-e "/^# ${escaped_header}$/,/^## /{//!d}" \
			-e "/^# ${escaped_header}$/d" \
			-e "/^## ${escaped_unreleased}$/,/^## /{//!d};" \
			-e "/^## ${escaped_unreleased}$/d"  \
			-e "/^## ${escaped_release}$/,/^## /{//!d};" \
			-e "/^## ${escaped_release}$/d"  \
			-e '${/^## $/d;}' \
			&& printf '\0'
	)

	# shellcheck disable=SC1003
	printf '%s\n' "${changelog_cleaned[@]}" > "${CHANGELOG_PATH}"
}

git-changelog() {
	: "${DEBUG:=0}"

	# Program related
	local PROGRAM_NAME="git-changelog"
	local CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/${PROGRAM_NAME}"

	# Default CHANGELOG file
	local GIT_TOP_LEVEL
	GIT_TOP_LEVEL=$(git rev-parse --show-toplevel)
	local CHANGELOG_PATH
	CHANGELOG_PATH="${GIT_TOP_LEVEL}/CHANGELOG.md"

	# Conventional commits
	local CONVENTIONAL_COMMIT_REGEX="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\(([[:alnum:]._-]+)\))?(!)?: ([[:print:]]*)"
	local CONVENTIONAL_COMMIT_TO_SHOW=("BREAKING_CHANGES" "feat" "fix" "revert" "test")

	# Git infos
	local GIT_ACTUAL_TAGS
	local GIT_ACTUAL_TAG
	local GIT_PREVIOUS_TAGS
	local GIT_PREVIOUS_TAG

	# Commit info
	local COMMIT_HASH=()
	local COMMIT_TITLE=()
	local COMMIT_BODY=()
	local COMMIT_SCOPE=()
	declare -A COMMIT_TYPE_LIST
	declare -A COMMIT_SCOPE_LIST

	set_git_infos
	set_commit_infos
	set_user_config
	if [[ "${#COMMIT_HASH[@]}" -gt 0 ]];then
		set_changelog_release
		update_changelog
		1>&2 echo "${CHANGELOG_PATH} updated !"
	else
		1>&2 echo "No changes made to ${CHANGELOG_PATH}"
	fi
}

git-changelog "$@"
