name: Release
on:
  push:
    branches:
      - master
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - shellcheck
          - test-bats-bash-4.4.23
    steps:
      - uses: actions/checkout@v2
      - name: make ${{matrix.target}}
        shell: 'script -qfec "bash {0}"'
        run: make ${{matrix.target}}
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Make release
        run: make release
      - uses: docker/login-action@v1
        with:
          username: rockandska
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish release
        run: |
          make docker-publish
      - name: Push back CHANGELOG and tag
        run: git push --follow-tags
